### PR TITLE
Feature: Box score for NBA All Star Games

### PR DESCRIPTION
**Pull request by rudiejd**
I have a project where I'm trying to give live predictions for the NBA All Star roster, and I figured I'd take the code I copy-pasted for scraping the roster and the box score, revise and refactor it, and throw it in here so I can depend on this awesome package and everyone can make use of it.

When a player is replaced from the ASG, the ASG stats are set to NAN, but the player name and team are still included so that projects using all-star status for classification can still use the `get_all_star_box_score` method for rosters. 

- Added and documented a method for getting the all star game box score for a given year
- Added test cases for the all star game roster including some edge cases (all passing right now)
- Refactored existing box score code for brevity and to minimize code reuse
- Changed the `get_stats` method so that it doesn't print to `STDOUT` when `ask_matches == False` so that it doesn't spam people when I use it to figure out an injured player's team.

### CODE REVIEW

**Comment by rudiejd** [comment]
One little comment: the way I figure out an injured/subbed player's team could not work if the player was traded before the all star game. I just use the the first team they played for that season. I could get their full game log and try to filter up to the date of the all-star game, but that would probably be super inefficient for a relatively uncommon case (I don't know if that's even happened)

**Comment by vishaalagartha** [comment]
Amazing work!

**Comment by rudiejd** [comment]
@vishaalagartha thank you! You might want to bump the version on pypi too when you get a chance, I think the last release was Jan 1, 2021.

**Comment by vishaalagartha** [comment]
@rudiejd , just released a new version. Thanks again!

**Pull request merged**
